language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
  - phpenv config-rm xdebug.ini

install:
  - mysql -e 'CREATE DATABASE changelanguage_testsuite;'
  - travis_wait composer update --prefer-stable
  - phpenv config-add /tmp/xdebug.ini
  - mkdir -p build/logs

script: phpunit --configuration phpunit.travis.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
